id: A00F901B0
title: A Prayer of Aspiration for the Mountain of Glory
type: translation
pechas:
- I9EF1C92C
- IE2E9A589
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 12:10:59.696644
  last_modified_at: 2023-01-04 12:10:59.696653
  collections:
  - Jamyang Khyentse Chökyi Lodrö Series
  - Works of Tibetan Masters
alignment_to_base:
  I9EF1C92C/6AA4: 3A91
  IE2E9A589/5354: 3A91
